name: Generate Updated Heatmap
run-name: Generating heatmap for commit ${{ github.sha }}
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:


jobs:
  generate-heatmap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: master
          submodules: true

      - name: Install Sigma
        run: pipx install sigma-cli

      - name: Update Heatmap
        run: sigma analyze attack count ./other/sigma_attack_nav_coverage.json rule*

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./other/sigma_attack_nav_coverage.json
          git add ./other/sigma_attack_nav_coverage.png
          if git diff --cached --quiet; then
            echo "No changes to commit."
            echo "PR_NEEDED=false" >> $GITHUB_ENV
          else
            git commit -m "Generated heatmap for commit ${{ github.sha }}"
            git checkout -B create-pull-request/update-heatmap
            git push -u origin create-pull-request/update-heatmap
          fi

      - name: Create Pull Request
        if: env.PR_NEEDED == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          reviewers: nasbench, frack113, phantinuss
          delete-branch: true
          commit-message: 'chore: update heatmap to use current tests'
          branch: 'create-pull-request/update-heatmap'
          title: 'Update Sigma Heatmap'
          body: |
            ### Summary of the Pull Request
  
            This PR updates sigma_attack_nav_coverage.json to include changes made to tests.
  
            ### Changelog
  
            chore: update heatmap to use current tests
  
            ### Example Log Event
  
            N/A
  
            ### Fixed Issues
  
            N/A
  
            ### SigmaHQ Rule Creation Conventions
            
            - If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_conventions.md)
